name: Remove

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Delete-Workflow:
    runs-on: ubuntu-20.04
    steps:
    - name: 删除工作流
      uses: FunctionXJB/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 2
        keep_minimum_runs: 1

    - name: 删除旧的发行版
      uses: dev-drprasad/delete-older-releases@master
      continue-on-error: true
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}